import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path
import json

st.set_page_config(page_title="PV Signal Detection", layout="wide")

st.title("🚀 Pharmacovigilance Signal Detection System")
st.markdown("**Regulatory-grade digital twin: Stats Engine + ML + Lineage**")

# Sidebar
st.sidebar.header("Navigation")
page = st.sidebar.selectbox(
    "Choose view",
    [
        "Dashboard",
        "Top Signals",
        "Signal Detail",
        "ML Features",
        "Audit Trail",
        "LangChain RAG",   # NEW
        "SAR Factory",     # NEW
        "PSMF v1.0",       # NEW
    ],
)

# ─────────────────────
# ORIGINAL PAGES
# ─────────────────────
if page == "Dashboard":
    st.header("📊 System Overview")

    col1, col2, col3, col4 = st.columns(4)
    signals = pd.read_csv("sar_reports/candidate_signals_2025Q1_stats_engine.csv")

    with col1:
        st.metric("Total Signals", len(signals))
    with col2:
        st.metric("PRR ≥ 2", f"{(signals['PRR'] >= 2).sum():,}")
    with col3:
        st.metric("Chi² ≥ 4", f"{(signals['CHISQ'] >= 4).sum():,}")
    with col4:
        st.metric("Cases ≥ 3", f"{(signals['CASES'] >= 3).sum():,}")

    fig = px.scatter(
        signals.head(1000),
        x="PRR",
        y="CHISQ",
        size="CASES",
        hover_data=["DRUG", "EVENT"],
        title="Signal Strength Distribution",
    )
    st.plotly_chart(fig, use_container_width=True)

elif page == "Top Signals":
    st.header("🔥 Top Candidate Signals")
    n = st.slider("Show top N", 10, 100, 20)
    candidates = pd.read_csv("sar_reports/candidate_signals_2025Q1_stats_engine.csv")
    st.dataframe(candidates.head(n), use_container_width=True)

elif page == "Signal Detail":
    st.header("🔍 Individual Signal Analysis")
    drug = st.text_input("Drug name", "InsulPen")
    event = st.text_input("Event name", "Incorrect dose administered")

    if st.button("Analyze Signal"):
        df = pd.read_csv("sar_reports/enriched_signals_2025Q1_stats_engine.csv")
        signal = df[
            (df["DRUG"].str.contains(drug, case=False, na=False))
            & (df["EVENT"].str.contains(event, case=False, na=False))
        ]
        if not signal.empty:
            st.success("Signal found!")
            st.dataframe(signal)
        else:
            st.warning("No signal found for this drug-event pair")

elif page == "ML Features":
    st.header("🤖 ML Feature Pipeline")
    features = pd.read_csv("ml_data/stats_engine_features.csv")

    st.metric("Training samples", features.shape[0])
    st.metric("Features", features.shape[1])

    col1, col2 = st.columns(2)
    with col1:
        fig1 = px.histogram(
            features, x="prr_rank", nbins=50, title="PRR Rank Distribution"
        )
        st.plotly_chart(fig1, use_container_width=True)
    with col2:
        fig2 = px.histogram(
            features, x="chi2_rank", nbins=50, title="Chi² Rank Distribution"
        )
        st.plotly_chart(fig2, use_container_width=True)

elif page == "Audit Trail":
    st.header("📋 Regulatory Compliance")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Data Lineage")
        lineage_file = Path("lineage/candidate_signals_2025Q1_stats_engine_lineage.json")
        if lineage_file.exists():
            with open(lineage_file) as f:
                lineage = json.load(f)
            st.json(lineage)
        else:
            st.info("Lineage file not found – run full pipeline first.")

    with col2:
        st.subheader("Governance")
        gov_file = Path("governance_dpia.md")
        if gov_file.exists():
            st.markdown(gov_file.read_text(encoding="utf-8"))
        else:
            st.info("governance_dpia.md not found – generated by pipeline.")

# ─────────────────────
# NEW PAGE 1: LangChain RAG
# ─────────────────────
elif page == "LangChain RAG":
    st.header("🧠 LangChain RAG (On‑demand SAR explanation)")
    st.info("Uses LangChain RAG module without changing the existing pipeline.")

    drug = st.text_input("Drug (for top signal)", "CALCIUM CHLORIDE")
    event = st.text_input("Event", "Keratopathy")

    if st.button("Generate SAR explanation (LangChain)"):
        try:
            from rag_langchain import PVSignalRAGLangChain  # separate module

            rag = PVSignalRAGLangChain()
            df = pd.read_csv("sar_reports/candidate_signals_2025Q1_stats_engine.csv")
            row = df[
                (df["DRUG"].str.contains(drug, case=False, na=False))
                & (df["EVENT"].str.contains(event, case=False, na=False))
            ].iloc[0]
            sar = rag.generate_sar(row)
            st.success("✅ LangChain SAR explanation generated")
            st.json(sar)
        except Exception as e:
            st.error(f"Error running LangChain RAG: {e}")
            st.info("Check rag_langchain.py, Ollama, and candidate_signals CSV.")

# ─────────────────────
# NEW PAGE 2: SAR Factory
# ─────────────────────
elif page == "SAR Factory":
    st.header("🏭 SAR Factory (batch generation)")
    st.info("Batch-generate SAR JSON files using LangChain when needed.")

    top_n = st.slider("Number of top signals", 5, 50, 20)

    if st.button("Generate SAR bundle"):
        try:
            from rag_langchain import PVSignalRAGLangChain

            rag = PVSignalRAGLangChain()
            bundle = rag.batch_generate(top_n)
            st.success(f"✅ Generated {bundle.get('total', 0)} SAR files")
            st.json({"total": bundle.get("total", 0), "generated_at": bundle.get("generated_at")})
        except Exception as e:
            st.error(f"Error generating SAR bundle: {e}")

    sar_count = len(list(Path("sar_reports").glob("*_SAR.json")))
    st.metric("Existing SAR files", sar_count)

# ─────────────────────
# NEW PAGE 3: PSMF v1.0
# ─────────────────────
elif page == "PSMF v1.0":
    st.header("📄 PSMF v1.0 (on‑demand)")

    if st.button("Generate PSMF v1.0"):
        try:
            from generate_psmf import main as generate_psmf_main  # separate module

            generate_psmf_main()
            st.success("✅ PSMF_v1.0.md generated")
        except Exception as e:
            st.error(f"Error generating PSMF: {e}")

    psmf_path = Path("PSMF_v1.0.md")
    if psmf_path.exists():
        text = psmf_path.read_text(encoding="utf-8")
        st.markdown(text)
        st.download_button(
            "Download PSMF_v1.0.md",
            data=text,
            file_name="PSMF_v1.0.md",
            mime="text/markdown",
        )
    else:
        st.info("PSMF_v1.0.md not found – click the button above to generate it.")

# Footer
st.markdown("---")
st.markdown(
    "*Regulatory PV Digital Twin | Stats Engine + ML + Lineage + LangChain add‑ons*"
)
